FROM python:3.6-slim

ARG WORKDIR=/opt/bin
ARG PROJECT=cloudformation
ARG AWS_CLOUDFORMATION_BUCKET_DOMAIN
ARG AWS_CLOUDFORMATION_BUCKET_NAME
ARG AWS_LAMBDA_BUCKET_NAME
ARG BUCKET=${AWS_CLOUDFORMATION_BUCKET_NAME}

ENV WORKDIR ${WORKDIR}
ENV AWS_CLOUDFORMATION_BUCKET_DOMAIN ${AWS_CLOUDFORMATION_BUCKET_DOMAIN}
ENV AWS_CLOUDFORMATION_BUCKET_NAME ${AWS_CLOUDFORMATION_BUCKET_NAME}
ENV AWS_LAMBDA_BUCKET_NAME ${AWS_LAMBDA_BUCKET_NAME}
ENV BUCKET ${BUCKET}

LABEL project=${PROJECT}
WORKDIR ${WORKDIR}

RUN true && \
  apt update && \
  apt install -y jq binutils && \
  pip3 install awscli && \
  mkdir ./build

COPY ./src/requirements.txt ${WORKDIR}
RUN pip3 install -r ./requirements.txt

COPY ./build/ ${WORKDIR}

ENTRYPOINT ["./cloudformation"]
CMD ["--help"]
